/* Create database SAPMEINT, SAPMEWIP and SAPMEODS */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SAPMEINT')
DROP DATABASE [SAPMEINT]
GO

USE [master]
GO

CREATE DATABASE [SAPMEINT] ON  PRIMARY 
( NAME = N'SAPMEINT', FILENAME = N'C:\SAP_MFG_DB\SAPMEINT.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'SAPMEINT_log', FILENAME = N'C:\SAP_MFG_DB\SAPMEINT_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [SAPMEINT] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAPMEINT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAPMEINT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAPMEINT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAPMEINT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAPMEINT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAPMEINT] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAPMEINT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SAPMEINT] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEINT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAPMEINT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEINT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAPMEINT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAPMEINT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAPMEINT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAPMEINT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAPMEINT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAPMEINT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SAPMEINT] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [SAPMEINT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAPMEINT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAPMEINT] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [SAPMEINT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAPMEINT] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SAPMEINT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAPMEINT] SET  READ_WRITE 
GO

ALTER DATABASE [SAPMEINT] SET RECOVERY FULL 
GO

ALTER DATABASE [SAPMEINT] SET  MULTI_USER 
GO

ALTER DATABASE [SAPMEINT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAPMEINT] SET DB_CHAINING OFF 
GO

/* CREATE SAP_ME_WIP */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SAPMEWIP')
DROP DATABASE [SAPMEWIP]
GO

USE [master]
GO

CREATE DATABASE [SAPMEWIP] ON  PRIMARY 
( NAME = N'SAPMEWIP', FILENAME = N'C:\SAP_MFG_DB\SAPMEWIP.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'SAPMEWIP_log', FILENAME = N'C:\SAP_MFG_DB\SAPMEWIP_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [SAPMEWIP] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAPMEWIP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAPMEWIP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAPMEWIP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAPMEWIP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAPMEWIP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAPMEWIP] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAPMEWIP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SAPMEWIP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEWIP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAPMEWIP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEWIP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAPMEWIP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAPMEWIP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAPMEWIP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAPMEWIP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAPMEWIP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAPMEWIP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SAPMEWIP] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [SAPMEWIP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAPMEWIP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAPMEWIP] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [SAPMEWIP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAPMEWIP] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SAPMEWIP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAPMEWIP] SET  READ_WRITE 
GO

ALTER DATABASE [SAPMEWIP] SET RECOVERY FULL 
GO

ALTER DATABASE [SAPMEWIP] SET  MULTI_USER 
GO

ALTER DATABASE [SAPMEWIP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAPMEWIP] SET DB_CHAINING OFF 
GO

/* CREATE SAP_ME_ODS */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SAPMEODS')
DROP DATABASE [SAPMEODS]
GO

USE [master]
GO

CREATE DATABASE [SAPMEODS] ON  PRIMARY 
( NAME = N'SAPMEODS', FILENAME = N'C:\SAP_MFG_DB\SAPMEODS.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'SAPMEODS_log', FILENAME = N'C:\SAP_MFG_DB\SAPMEODS_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [SAPMEODS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAPMEODS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAPMEODS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAPMEODS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAPMEODS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAPMEODS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAPMEODS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAPMEODS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SAPMEODS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEODS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAPMEODS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAPMEODS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAPMEODS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAPMEODS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAPMEODS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAPMEODS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAPMEODS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAPMEODS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SAPMEODS] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [SAPMEODS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAPMEODS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAPMEODS] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [SAPMEODS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAPMEODS] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SAPMEODS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAPMEODS] SET  READ_WRITE 
GO

ALTER DATABASE [SAPMEODS] SET RECOVERY FULL 
GO

ALTER DATABASE [SAPMEODS] SET  MULTI_USER 
GO

ALTER DATABASE [SAPMEODS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAPMEODS] SET DB_CHAINING OFF 
GO

/* Create database logins SAPMEINT, SAPMEWIP and SAPMEODS */
/* create login SAPMEINT */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SAPMEINT')
DROP LOGIN [SAPMEINT]
GO

CREATE LOGIN [SAPMEINT] WITH PASSWORD='MFG123456', DEFAULT_DATABASE=[SAPMEINT], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [SAPMEINT] ENABLE
GO

/* create login SAPMEODS */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SAPMEODS')
DROP LOGIN [SAPMEODS]
GO

CREATE LOGIN [SAPMEODS] WITH PASSWORD='MFG123456', DEFAULT_DATABASE=[SAPMEODS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [SAPMEODS] ENABLE
GO

/* create login SAPMEWIP */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SAPMEWIP')
DROP LOGIN [SAPMEWIP]
GO

CREATE LOGIN [SAPMEWIP] WITH PASSWORD='MFG123456', DEFAULT_DATABASE=[SAPMEWIP], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [SAPMEWIP] ENABLE
GO

/* Create user mappings after sqlserver sql registered */
/* SAPMEINT */
USE [master]
GO 
create user [SAPMEINT] from login [SAPMEINT];
exec sp_addrolemember [SqlJDBCXAUser], 'SAPMEINT'

USE [SAPMEINT]
GO 
create user [SAPMEINT] from login [SAPMEINT];
exec sp_addrolemember [db_owner], 'SAPMEINT'

/* SAPMEODS */
USE [master]
GO 
create user [SAPMEODS] from login [SAPMEODS];
exec sp_addrolemember [SqlJDBCXAUser], 'SAPMEODS'

USE [SAPMEODS]
GO 
create user [SAPMEODS] from login [SAPMEODS];
exec sp_addrolemember [db_owner], 'SAPMEODS'

USE [SAPMEWIP]
GO 
create user [SAPMEODS] from login [SAPMEODS];
exec sp_addrolemember [db_datareader], 'SAPMEODS'

/* SAPMEWIP */
USE [master]
GO 
create user [SAPMEWIP] from login [SAPMEWIP];
exec sp_addrolemember [SqlJDBCXAUser], 'SAPMEWIP'

USE [SAPMEWIP]
GO 
create user [SAPMEWIP] from login [SAPMEWIP];
exec sp_addrolemember [db_owner], 'SAPMEWIP'

USE [SAPMEINT]
GO 
create user [SAPMEWIP] from login [SAPMEWIP];
exec sp_addrolemember [db_owner], 'SAPMEWIP'

USE [SAPMEODS]
GO 
create user [SAPMEWIP] from login [SAPMEWIP];
exec sp_addrolemember [db_owner], 'SAPMEWIP'

/* maybe we need to fix the orphan users first...in case you find error like 'User, group, or role 'SAP_ME_${XXX}' already exists in the current database'  */
USE [master]
GO 
exec sp_change_users_login 'AUTO_FIX', 'SAPMEINT' 
exec sp_change_users_login 'AUTO_FIX', 'SAPMEODS' 
exec sp_change_users_login 'AUTO_FIX', 'SAPMEWIP'






