/* Create database AMU_ME_INT, AMU_ME_WIP and AMU_ME_ODS */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AMU_ME_INT')
DROP DATABASE [AMU_ME_INT]
GO

USE [master]
GO

CREATE DATABASE [AMU_ME_INT] ON  PRIMARY 
( NAME = N'AMU_ME_INT', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_INT.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'AMU_ME_INT_log', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_INT_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [AMU_ME_INT] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AMU_ME_INT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AMU_ME_INT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET ARITHABORT OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_INT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_INT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AMU_ME_INT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AMU_ME_INT] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [AMU_ME_INT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [AMU_ME_INT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AMU_ME_INT] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AMU_ME_INT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AMU_ME_INT] SET  READ_WRITE 
GO

ALTER DATABASE [AMU_ME_INT] SET RECOVERY FULL 
GO

ALTER DATABASE [AMU_ME_INT] SET  MULTI_USER 
GO

ALTER DATABASE [AMU_ME_INT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AMU_ME_INT] SET DB_CHAINING OFF 
GO

/* CREATE SAP_ME_WIP */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AMU_ME_WIP')
DROP DATABASE [AMU_ME_WIP]
GO

USE [master]
GO

CREATE DATABASE [AMU_ME_WIP] ON  PRIMARY 
( NAME = N'AMU_ME_WIP', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_WIP.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'AMU_ME_WIP_log', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_WIP_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [AMU_ME_WIP] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AMU_ME_WIP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AMU_ME_WIP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET ARITHABORT OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_WIP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_WIP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AMU_ME_WIP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AMU_ME_WIP] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [AMU_ME_WIP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [AMU_ME_WIP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AMU_ME_WIP] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AMU_ME_WIP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AMU_ME_WIP] SET  READ_WRITE 
GO

ALTER DATABASE [AMU_ME_WIP] SET RECOVERY FULL 
GO

ALTER DATABASE [AMU_ME_WIP] SET  MULTI_USER 
GO

ALTER DATABASE [AMU_ME_WIP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AMU_ME_WIP] SET DB_CHAINING OFF 
GO

/* CREATE SAP_ME_ODS */
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AMU_ME_ODS')
DROP DATABASE [AMU_ME_ODS]
GO

USE [master]
GO

CREATE DATABASE [AMU_ME_ODS] ON  PRIMARY 
( NAME = N'AMU_ME_ODS', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_ODS.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'AMU_ME_ODS_log', FILENAME = N'D:\SAP_MFG_DB\AMU_ME_ODS_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CI_AS
GO

ALTER DATABASE [AMU_ME_ODS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AMU_ME_ODS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AMU_ME_ODS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET ARITHABORT OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_ODS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AMU_ME_ODS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AMU_ME_ODS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AMU_ME_ODS] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [AMU_ME_ODS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [AMU_ME_ODS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AMU_ME_ODS] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AMU_ME_ODS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AMU_ME_ODS] SET  READ_WRITE 
GO

ALTER DATABASE [AMU_ME_ODS] SET RECOVERY FULL 
GO

ALTER DATABASE [AMU_ME_ODS] SET  MULTI_USER 
GO

ALTER DATABASE [AMU_ME_ODS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AMU_ME_ODS] SET DB_CHAINING OFF 
GO

/* Create database logins AMU_ME_INT, AMU_ME_WIP and AMU_ME_ODS */
/* create login AMU_ME_INT */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AMU_ME_INT')
DROP LOGIN [AMU_ME_INT]
GO

CREATE LOGIN [AMU_ME_INT] WITH PASSWORD='AMU345678', DEFAULT_DATABASE=[AMU_ME_INT], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [AMU_ME_INT] ENABLE
GO

/* create login AMU_ME_ODS */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AMU_ME_ODS')
DROP LOGIN [AMU_ME_ODS]
GO

CREATE LOGIN [AMU_ME_ODS] WITH PASSWORD='AMU345678', DEFAULT_DATABASE=[AMU_ME_ODS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [AMU_ME_ODS] ENABLE
GO

/* create login AMU_ME_WIP */
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AMU_ME_WIP')
DROP LOGIN [AMU_ME_WIP]
GO

CREATE LOGIN [AMU_ME_WIP] WITH PASSWORD='AMU345678', DEFAULT_DATABASE=[AMU_ME_WIP], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [AMU_ME_WIP] ENABLE
GO

/* Create user mappings after sqlserver sql registered */
/* AMU_ME_INT */
USE [master]
GO 
create user [AMU_ME_INT] from login [AMU_ME_INT];
exec sp_addrolemember [SqlJDBCXAUser], 'AMU_ME_INT'

USE [AMU_ME_INT]
GO 
create user [AMU_ME_INT] from login [AMU_ME_INT];
exec sp_addrolemember [db_owner], 'AMU_ME_INT'

/* AMU_ME_ODS */
USE [master]
GO 
create user [AMU_ME_ODS] from login [AMU_ME_ODS];
exec sp_addrolemember [SqlJDBCXAUser], 'AMU_ME_ODS'

USE [AMU_ME_ODS]
GO 
create user [AMU_ME_ODS] from login [AMU_ME_ODS];
exec sp_addrolemember [db_owner], 'AMU_ME_ODS'

USE [AMU_ME_WIP]
GO 
create user [AMU_ME_ODS] from login [AMU_ME_ODS];
exec sp_addrolemember [db_datareader], 'AMU_ME_ODS'

/* AMU_ME_WIP */
USE [master]
GO 
create user [AMU_ME_WIP] from login [AMU_ME_WIP];
exec sp_addrolemember [SqlJDBCXAUser], 'AMU_ME_WIP'

USE [AMU_ME_WIP]
GO 
create user [AMU_ME_WIP] from login [AMU_ME_WIP];
exec sp_addrolemember [db_owner], 'AMU_ME_WIP'

USE [AMU_ME_INT]
GO 
create user [AMU_ME_WIP] from login [AMU_ME_WIP];
exec sp_addrolemember [db_owner], 'AMU_ME_WIP'

USE [AMU_ME_ODS]
GO 
create user [AMU_ME_WIP] from login [AMU_ME_WIP];
exec sp_addrolemember [db_owner], 'AMU_ME_WIP'

/* maybe we need to fix the orphan users first...in case you find error like 'User, group, or role 'SAP_ME_${XXX}' already exists in the current database'  */
USE [master]
GO 
exec sp_change_users_login 'AUTO_FIX', 'AMU_ME_INT' 
exec sp_change_users_login 'AUTO_FIX', 'AMU_ME_ODS' 
exec sp_change_users_login 'AUTO_FIX', 'AMU_ME_WIP'






